### ISSUE TITLE
Opening Catalogue Failure

### ISSUE THREAD

**Issue by veroog** [ispingos/pytheas-splitting#4]
After downloading a xml catalog using Obspy, I cannot open it in Pytheas.

This is the error I'm getting: 

Opening catalogue exited with exception:
 Traceback (most recent call last):
  File "pytheas/pytheas.py", line 4511, in ocWinOk
    self.openCat()
  File "pytheas/pytheas.py", line 2682, in openCat
    self.getCat(self.dataPath,self.catFile,self.dbPath)
  File "pytheas/pytheas.py", line 2669, in getCat
    self.evsDict,self.statsDict
  File "pytheas/pytheas.py", line 1042, in eventCorrect
    directoryKeys=np.asarray([UTCDateTime(y).timestamp for y in sorted(evPath)])
  File "pytheas/pytheas.py", line 1042, in <listcomp>
    directoryKeys=np.asarray([UTCDateTime(y).timestamp for y in sorted(evPath)])
  File "/Users/veronica/opt/anaconda3/lib/python3.7/site-packages/obspy/core/utcdatetime.py", line 421, in __init__
    dt = datetime.datetime(*args, **kwargs)
TypeError: an integer is required (got type str)

This is how I downloaded the catalog using Obspy:

t1=obspy.UTCDateTime('2018-10-14T00:00:00')
t2 =obspy.UTCDateTime('2019-10-14T00:00:00')
client = Client('IRIS')
arrivals=False
events = client.get_events(starttime=t1, endtime=t2,minlatitude=30, maxlatitude=32,
                           minlongitude=-104, maxlongitude=-101,  includearrivals=arrivals
                        )
events.write('test3.xml', format = 'QUAKEML')

**Log File**
[20201019163658_Pytheas.log](https://github.com/ispingos/pytheas-splitting/files/5403417/20201019163658_Pytheas.log)

**Operating System (please complete the following information):**
 - macOS Catalina, Version 10.15.5

**Dependencies (please complete the following information):**
 - Python Version: 3.7.7
 - Obspy Version: 1.2.2
 - PyQt5 Version: 5.15.1

**Comment by veroog** [comment]
Issue had to do with the data folder structure.

**Comment by ispingos** [comment]
Thanks for the update!
